##
## EPITECH PROJECT, 2023
## Makfile
## File description:
## Makefile for project 201Yams
##

NAME	=	201yams

all:
		cp yams.py $(NAME)
		chmod +x $(NAME)

clean:
		$(RM) -r __pycache__

fclean:		clean
		$(RM) $(NAME)
		$(RM) -rf ./sources/__pycache__

re:		fclean all